version: '3'

services:

  app-dev:
    build: .
    profiles: ["dev"]
    ports:
      - "8080:8080"

  app-prod:
    image: artenesnogueira/anotes:2.0.1
    profiles: ["prod"]
    ports:
      - "8080:8080"

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db

  minio:
    image: bitnami/minio
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key

volumes:
  mongo:
  minio: